### ISSUE TITLE
Pointer bug report

### ISSUE THREAD

**Issue by globalcaos** [SkymindIO/nd4j#15]
What you do in [BaseNDArray.java line #2693](https://github.com/SkymindIO/nd4j/blob/master/nd4j-api/src/main/java/org/nd4j/linalg/api/ndarray/BaseNDArray.java#L2693) I think is wrong, because you are returning a pointer to an element that was passed expecting not to be modified.

To my understanding, you should be returning a copy of _other_, which you can then modify. From the _ElementWiseOperationExample.java_ [call](http://grepcode.com/file/repo1.maven.org/maven2/org.nd4j/nd4j-examples/0.0.3.5.1/org/nd4j/examples/ElementWiseOperationExample.java#43) in line #43 you might be modifying _nd2_ (if the condition was true), which from the IntelliJ debugger can be identified as the _{JCublasNDArray@502}_ memory position.

If it was in C++, I would be adding _const_ declarations in [BaseNDArray.java line #2286](https://github.com/SkymindIO/nd4j/blob/master/nd4j-api/src/main/java/org/nd4j/linalg/api/ndarray/BaseNDArray.java#L2286) like:

     public INDArray addColumnVector(const INDArray columnVector) {

This way you would be automatically notified by the compiler when you are modifying the variable. It would however not cover the fact that you still might be able to return the same pointer without modification, that should probably be dealt with separately.

You might want to use _final_, but I am afraid it is not the same thing as _const_ in C++. Read this [discussion](http://stackoverflow.com/questions/2735736/why-is-there-no-constant-keyword-in-java), I don't fully understand the difference.

Additionally, I imagine there is a chance this mistake is not isolated because it is a conceptual one. It can mess things up a bit if encountered in other circumstances, not having a clue where the cause is, so I would recommend a more global review on the code.

**Comment by agibsonccc** [comment]
Fixed.
